apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-clientes
  namespace: proyecto-sa
spec:
  selector:
    matchLabels:
      name: deploy-clientes
  replicas: 1
  template:
    metadata:
      labels:
        name: deploy-clientes
    spec:
      containers:
      - name: clientes
        image: josephmarroquin/f2-client
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: DB_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: JWT_SECRET
        - name: S3_BUCKET_NAME
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: S3_BUCKET_NAME
        - name: S3_REGION
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: S3_REGION
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-general
              key: S3_SECRET_KEY