apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-proveedores
spec:
  ports:
  - name: proveedores-port
    port: 8081
    targetPort: 8081
  selector:
      name: deploy-proveedores
  type: NodePort