apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-adminpanel
spec:
  ports:
  - name: adminpanel-port
    port: 3003
    targetPort: 3003
  selector:
      name: deploy-adminpanel
  type: NodePort