apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-consumir
spec:
  ports:
  - name: consumir-port
    port: 3002
    targetPort: 3002
  selector:
      name: deploy-consumir
  type: NodePort