apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-pagos
spec:
  ports:
  - name: pagos-port
    port: 5002
    targetPort: 5002
  selector:
      name: deploy-pagos
  type: NodePort