apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-clientes
spec:
  ports:
  - name: clientes-port
    port: 5000
    targetPort: 5000
  selector:
      name: deploy-clientes
  type: NodePort