apiVersion: v1
kind: Service
metadata:
  namespace: proyecto-sa
  name: service-notificaciones
spec:
  ports:
  - name: notificaciones-port
    port: 5001
    targetPort: 5001
  selector:
      name: deploy-notificaciones
  type: NodePort